//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTECHMVC_CRUD_Final.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_ClassRoutine
    {
        public int ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
